# Generated by Django 5.1 on 2024-09-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0010_remove_video_comments_video_comments_count_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='likes',
        ),
    ]
