# Generated by Django 5.1 on 2024-09-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0012_video_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='likes',
        ),
    ]
